### ISSUE TITLE
Changelog in PR body is wrong when using unified changelog

### ISSUE THREAD

**Issue by beeb** [release-plz/release-plz#2307]
## Bug description

When using the same CHANGELOG.md path for multiple crates in the same workspace, the PR body shows a wrong or empty Changelog.
It seems to be that `parse-changelog` cannot parse this format, and returns an empty result, at least when I run it standalone.

Note that I had to manually back-fill the changelog because we started using release-plz only recently. Did my best to match the format.

- Would you like to work on a fix? If the fix is straightforward, yes, but can't spend too much time on this atm. Any pointers would be welcome to assess this.

## To Reproduce

1. See empty changelog in PR body here: https://github.com/mario-eth/soldeer/pull/295
1. See CI run here https://github.com/mario-eth/soldeer/actions/runs/16189230713/job/45700887136

Locally:

1. Clone this commit: https://github.com/mario-eth/soldeer/tree/1e219527b89e49b91e9ad8df62633efc24ccc9c5
1. `cargo binstall parse-changelog` (CLI of the library which release-plz uses)
1. `parse-changelog CHANGELOG.md`
1. `error: not found release; to get 'Unreleased' section specify release explicitly: \`parse-changelog CHANGELOG.md Unreleased\``

## Expected behavior

The changelog in the PR body should not be empty.

## Screenshots

<img width="930" height="412" alt="Image" src="https://github.com/user-attachments/assets/3a4a8a6b-ca96-4890-ab59-70118e68a461" />

## Environment

- OS: ubuntu-latest (Github Actions)
- release-plz version: 0.3.136

**Comment by marcoieni** [comment]
oh, that's unfortunate. Yeah apparently the fix is not straightforward. PR welcome anyway!
Let's make sure we add a test for this, too

**Comment by beeb** [comment]
What do you think would be the best way to tackle this?

Pre-process the changelog to remove the package name? But since the changelog format can be customized, there is probably no way to make it work universally.

Allowing to configure the parser to set a prefix could maybe work. Could maybe parse the changelog once per package, with a different prefix each time. This seems to work with the CLI: ``parse-changelog --prefix '`soldeer-core` - ' CHANGELOG.md``

Since the prefix can be a regex, it's possible to match all the versions, but then it complains about the fact that there are multiple release notes for any given version: ``parse-changelog --prefix '`soldeer(-core)?` - ' CHANGELOG.md``

Maybe just use the diff from the changelog file and no try to parse it? Or at least do this as fallback when the parsing fails to return something.

**Comment by beeb** [comment]
I think a good way to make it configurable and thus universal would be to have a config option for the parser prefix regex, which itself is a template with the same scope as the changelog template.

In my case I would set the prefix to `` `{{ package }}` - `` and then release-plz would fill-in the template + parse the changelog for each package. The tricky thing would be to escape the package name so that it matches literally, in the eventuality where it contains regex tokens.

Alternatively, or in the meantime, maybe just fallback to using the changelog diff string directly?

**Comment by marcoieni** [comment]
In [#2367](https://github.com/release-plz/release-plz/pull/2367) I implemented the fallback mechanism.
Sorry for not replying to you earlier about this, but I found some time to work on this yesterday.

Please test this when the new action will be released (I didn't include this in this release because it was already packed) and let me know how we can improve it (PR welcome, too of course!).

You can already test it locally compiling from master of course.

The changelog prefix config seems too complicated just to get the PR body changelog preview better.
But if there's the need for it we can open a new issue.

**Comment by beeb** [comment]
Thanks a lot for the fix! I'll be sure to report when the new action is available.

**Comment by beeb** [comment]
Hey @marcoieni ! Did the first release after the fix, and it seems the PR body is now correct 🎉 

<img width="501" height="523" alt="Image" src="https://github.com/user-attachments/assets/fb760e6b-0b10-4832-8cb5-6c3cdddae698" />

However, I'm still missing the changelog data in the actual release body.

<img width="948" height="344" alt="Image" src="https://github.com/user-attachments/assets/5913ae32-b9fd-4adc-a324-84fedc792c48" />

Thanks
